### ISSUE TITLE
Wrong length in Protocol.encode

### ISSUE THREAD

**Issue by spacemeowx2** [myour-cc/tedis#24]
If you are storing multibyte character like Chinese, the redis server will return error: `UnhandledPromiseRejectionWarning: ERR Protocol error: unbalanced quotes in request`

https://github.com/myour-cc/tedis/blob/8a082969382b15ced4a75299c23feaa3a18c8643/src/core/protocol.ts#L122

https://github.com/myour-cc/tedis/blob/8a082969382b15ced4a75299c23feaa3a18c8643/src/core/protocol.ts#L125

I suggest replace `parameter.length` with `Buffer.byteLength(parameter)`.

**Comment by dasoncheng** [comment]
thanks for your advice, I'm going to rewrite the protocol with Buffer
